### ISSUE TITLE
break with marked@0.3.4

### ISSUE THREAD

**Issue by tgfjt** [mikaelbr/marked-terminal#18]
Hi.:smile_cat: 

I got Error below:
```
/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:1226
    throw e;
          ^
TypeError: this.renderer.text is not a function
Please report this to https://github.com/chjj/marked.
    at InlineLexer.output (/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:685:28)
    at Parser.tok (/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:985:21)
    at Parser.parse (/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:922:17)
    at marked (/Users/tgfjt/workspace/marked-sample/node_modules/marked/lib/marked.js:1218:19)
    at Object.<anonymous> (/Users/tgfjt/workspace/marked-sample/sample.js:10:13)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

sample.js:
```js
var marked = require('marked');
var TerminalRenderer = require('marked-terminal');

marked.setOptions({
  renderer: new TerminalRenderer()
});

console.log(marked('# Hello  This is **markdown** printed in the `terminal`'));
```

This code works successfully on marked `v0.3.3`.

This issue is caused by new method `renderer.text` on marked `v0.3.4`.
https://github.com/chjj/marked/blob/master/lib/marked.js#L685

**Comment by mikaelbr** [comment]
Ah, thanks for letting me know. Fixed in `v1.6.0`:

```shell
➜  marked-terminal git:(master) npm publish
+ marked-terminal@1.6.0
```

**Comment by tgfjt** [comment]
Thanks for you fixing so quickly! :tada:

**Comment by finnp** [comment]
:tada:
